import editorWorker from 'monaco-editor-core/esm/vs/editor/editor.worker?worker';
import vueWorker from './vue.worker?worker';
import * as onigasm from "onigasm";
import onigasmWasm from "onigasm/lib/onigasm.wasm?url";
import { editor, languages, Uri } from 'monaco-editor-core';
import * as volar from '@volar/monaco';
import { Store } from '../store';
import * as VolarWorker from '@volar/monaco/worker';
import { getOrCreateModel } from './utils';

export function loadWasm() {
  return onigasm.loadWASM(onigasmWasm);
}

export function loadMonacoEnv(store: Store) {
  (self as any).MonacoEnvironment = {
    async getWorker(_: any, label: string) {
      if (label === 'vue') {
        return new vueWorker();
      }
      return new editorWorker();
    },
  };
  languages.register({ id: 'vue', extensions: ['.vue'] })
  languages.onLanguage('vue', async () => {
    const worker = editor.createWebWorker<any>({
      moduleId: 'vs/language/vue/vueWorker',
      label: 'vue',
      host: createDtsHost(),
    });
    const languageId = ['vue'];
    const getSyncUris = () => Object.keys(store.state.files).map(filename => Uri.parse(`file:///${filename}`));
    volar.editor.activateMarkers(worker, languageId, 'vue', getSyncUris, editor);
    volar.editor.activateAutoInsertion(worker, languageId, getSyncUris, editor);
    volar.languages.registerProvides(worker, languageId, getSyncUris, languages);
  })

  function createDtsHost() {
    const dtsHost = VolarWorker.createDtsHost('https://unpkg.com/', !store.vueVersion ? {} : {
      'vue': store.vueVersion,
      '@vue/compiler-core': store.vueVersion,
      '@vue/compiler-dom': store.vueVersion,
      '@vue/compiler-sfc': store.vueVersion,
      '@vue/compiler-ssr': store.vueVersion,
      '@vue/reactivity': store.vueVersion,
      '@vue/runtime-core': store.vueVersion,
      '@vue/runtime-dom': store.vueVersion,
      '@vue/shared': store.vueVersion,
    }, (filename, text) => {
      getOrCreateModel(Uri.file(filename), undefined, text);
    });
    for (const ignorePath of ignoreNodeModulePaths) {
      dtsHost.files.set(ignorePath, undefined);
    }
    return dtsHost;
  }
}

// Preset failed file paths to speed up dts acquisition
// Note: If the file structure of the new vue version changes, this list should be regenerated.
const ignoreNodeModulePaths = [
  "/node_modules/vue.d.ts",
  "/node_modules/vue/index.d.ts",
  "/node_modules/@types/vue.d.ts",
  "/node_modules/@types/vue/index.d.ts",
  "/node_modules/@vue/runtime-core.d.ts",
  "/node_modules/@vue/runtime-core/index.d.ts",
  "/node_modules/@types/vue__runtime-core/package.json",
  "/node_modules/@types/vue__runtime-core.d.ts",
  "/node_modules/@types/vue__runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-dom.d.ts",
  "/node_modules/@vue/runtime-dom/index.d.ts",
  "/node_modules/@types/vue__runtime-dom/package.json",
  "/node_modules/@types/vue__runtime-dom.d.ts",
  "/node_modules/@types/vue__runtime-dom/index.d.ts",
  "/node_modules/vue/dist/vue.d.ts.d.ts",
  "/node_modules/vue/dist/vue.d.ts/index.d.ts",
  "/node_modules/@vue/runtime-core/dist/runtime-core.d.ts.d.ts",
  "/node_modules/@vue/runtime-core/dist/runtime-core.d.ts/index.d.ts",
  "/node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts.d.ts",
  "/node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts/index.d.ts",
  "/node_modules/@typescript/lib-es5/package.json",
  "/node_modules/@typescript/lib-es5.d.ts",
  "/node_modules/@typescript/lib-es5/index.d.ts",
  "/node_modules/@types/typescript__lib-es5/package.json",
  "/node_modules/@types/typescript__lib-es5.d.ts",
  "/node_modules/@types/typescript__lib-es5/index.d.ts",
  "/node_modules/@typescript/lib-dom/package.json",
  "/node_modules/@typescript/lib-dom.d.ts",
  "/node_modules/@typescript/lib-dom/index.d.ts",
  "/node_modules/@types/typescript__lib-dom/package.json",
  "/node_modules/@types/typescript__lib-dom.d.ts",
  "/node_modules/@types/typescript__lib-dom/index.d.ts",
  "/node_modules/@typescript/lib-webworker/importscripts/package.json",
  "/node_modules/@typescript/lib-webworker/package.json",
  "/node_modules/@typescript/lib-webworker/importscripts.d.ts",
  "/node_modules/@typescript/lib-webworker/importscripts/index.d.ts",
  "/node_modules/@types/typescript__lib-webworker/importscripts/package.json",
  "/node_modules/@types/typescript__lib-webworker/package.json",
  "/node_modules/@types/typescript__lib-webworker/importscripts.d.ts",
  "/node_modules/@types/typescript__lib-webworker/importscripts/index.d.ts",
  "/node_modules/@typescript/lib-scripthost/package.json",
  "/node_modules/@typescript/lib-scripthost.d.ts",
  "/node_modules/@typescript/lib-scripthost/index.d.ts",
  "/node_modules/@types/typescript__lib-scripthost/package.json",
  "/node_modules/@types/typescript__lib-scripthost.d.ts",
  "/node_modules/@types/typescript__lib-scripthost/index.d.ts",
  "/node_modules/vue/dist/node_modules/@vue/compiler-dom/package.json",
  "/node_modules/vue/dist/node_modules/@vue/compiler-dom.d.ts",
  "/node_modules/vue/dist/node_modules/@vue/compiler-dom/index.d.ts",
  "/node_modules/vue/dist/node_modules/@types/vue__compiler-dom/package.json",
  "/node_modules/vue/dist/node_modules/@types/vue__compiler-dom.d.ts",
  "/node_modules/vue/dist/node_modules/@types/vue__compiler-dom/index.d.ts",
  "/node_modules/vue/node_modules/@vue/compiler-dom/package.json",
  "/node_modules/vue/node_modules/@vue/compiler-dom.d.ts",
  "/node_modules/vue/node_modules/@vue/compiler-dom/index.d.ts",
  "/node_modules/vue/node_modules/@types/vue__compiler-dom/package.json",
  "/node_modules/vue/node_modules/@types/vue__compiler-dom.d.ts",
  "/node_modules/vue/node_modules/@types/vue__compiler-dom/index.d.ts",
  "/node_modules/@vue/compiler-dom.d.ts",
  "/node_modules/@vue/compiler-dom/index.d.ts",
  "/node_modules/@types/vue__compiler-dom/package.json",
  "/node_modules/@types/vue__compiler-dom.d.ts",
  "/node_modules/@types/vue__compiler-dom/index.d.ts",
  "/node_modules/vue/dist/node_modules/@vue/runtime-dom/package.json",
  "/node_modules/vue/dist/node_modules/@vue/runtime-dom.d.ts",
  "/node_modules/vue/dist/node_modules/@vue/runtime-dom/index.d.ts",
  "/node_modules/vue/dist/node_modules/@types/vue__runtime-dom/package.json",
  "/node_modules/vue/dist/node_modules/@types/vue__runtime-dom.d.ts",
  "/node_modules/vue/dist/node_modules/@types/vue__runtime-dom/index.d.ts",
  "/node_modules/vue/node_modules/@vue/runtime-dom/package.json",
  "/node_modules/vue/node_modules/@vue/runtime-dom.d.ts",
  "/node_modules/vue/node_modules/@vue/runtime-dom/index.d.ts",
  "/node_modules/vue/node_modules/@types/vue__runtime-dom/package.json",
  "/node_modules/vue/node_modules/@types/vue__runtime-dom.d.ts",
  "/node_modules/vue/node_modules/@types/vue__runtime-dom/index.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@vue/runtime-core/package.json",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@vue/runtime-core.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@vue/runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/vue__runtime-core/package.json",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/vue__runtime-core.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/vue__runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/package.json",
  "/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@types/vue__runtime-core/package.json",
  "/node_modules/@vue/runtime-dom/node_modules/@types/vue__runtime-core.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@types/vue__runtime-core/index.d.ts",
  "/node_modules/@vue/node_modules/@vue/runtime-core/package.json",
  "/node_modules/@vue/node_modules/@vue/runtime-core.d.ts",
  "/node_modules/@vue/node_modules/@vue/runtime-core/index.d.ts",
  "/node_modules/@vue/node_modules/@types/vue__runtime-core/package.json",
  "/node_modules/@vue/node_modules/@types/vue__runtime-core.d.ts",
  "/node_modules/@vue/node_modules/@types/vue__runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/csstype/package.json",
  "/node_modules/@vue/runtime-dom/dist/node_modules/csstype.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/csstype/index.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/csstype/package.json",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/csstype.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/csstype/index.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/csstype/package.json",
  "/node_modules/@vue/runtime-dom/node_modules/csstype.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/csstype/index.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@types/csstype/package.json",
  "/node_modules/@vue/runtime-dom/node_modules/@types/csstype.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@types/csstype/index.d.ts",
  "/node_modules/@vue/node_modules/csstype/package.json",
  "/node_modules/@vue/node_modules/csstype.d.ts",
  "/node_modules/@vue/node_modules/csstype/index.d.ts",
  "/node_modules/@vue/node_modules/@types/csstype/package.json",
  "/node_modules/@vue/node_modules/@types/csstype.d.ts",
  "/node_modules/@vue/node_modules/@types/csstype/index.d.ts",
  "/node_modules/csstype.d.ts",
  "/node_modules/@types/csstype/package.json",
  "/node_modules/@types/csstype.d.ts",
  "/node_modules/@types/csstype/index.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@vue/reactivity/package.json",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@vue/reactivity.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@vue/reactivity/index.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/vue__reactivity/package.json",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/vue__reactivity.d.ts",
  "/node_modules/@vue/runtime-dom/dist/node_modules/@types/vue__reactivity/index.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@vue/reactivity/package.json",
  "/node_modules/@vue/runtime-dom/node_modules/@vue/reactivity.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@vue/reactivity/index.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@types/vue__reactivity/package.json",
  "/node_modules/@vue/runtime-dom/node_modules/@types/vue__reactivity.d.ts",
  "/node_modules/@vue/runtime-dom/node_modules/@types/vue__reactivity/index.d.ts",
  "/node_modules/@vue/node_modules/@vue/reactivity/package.json",
  "/node_modules/@vue/node_modules/@vue/reactivity.d.ts",
  "/node_modules/@vue/node_modules/@vue/reactivity/index.d.ts",
  "/node_modules/@vue/node_modules/@types/vue__reactivity/package.json",
  "/node_modules/@vue/node_modules/@types/vue__reactivity.d.ts",
  "/node_modules/@vue/node_modules/@types/vue__reactivity/index.d.ts",
  "/node_modules/@vue/reactivity.d.ts",
  "/node_modules/@vue/reactivity/index.d.ts",
  "/node_modules/@types/vue__reactivity/package.json",
  "/node_modules/@types/vue__reactivity.d.ts",
  "/node_modules/@types/vue__reactivity/index.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/shared/package.json",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/shared.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/shared/index.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__shared/package.json",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__shared.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__shared/index.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@vue/shared/package.json",
  "/node_modules/@vue/runtime-core/node_modules/@vue/shared.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@vue/shared/index.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__shared/package.json",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__shared.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__shared/index.d.ts",
  "/node_modules/@vue/node_modules/@vue/shared/package.json",
  "/node_modules/@vue/node_modules/@vue/shared.d.ts",
  "/node_modules/@vue/node_modules/@vue/shared/index.d.ts",
  "/node_modules/@vue/node_modules/@types/vue__shared/package.json",
  "/node_modules/@vue/node_modules/@types/vue__shared.d.ts",
  "/node_modules/@vue/node_modules/@types/vue__shared/index.d.ts",
  "/node_modules/@vue/shared.d.ts",
  "/node_modules/@vue/shared/index.d.ts",
  "/node_modules/@types/vue__shared/package.json",
  "/node_modules/@types/vue__shared.d.ts",
  "/node_modules/@types/vue__shared/index.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/runtime-core/package.json",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/runtime-core.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__runtime-core/package.json",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__runtime-core.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@vue/runtime-core/package.json",
  "/node_modules/@vue/runtime-core/node_modules/@vue/runtime-core.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@vue/runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__runtime-core/package.json",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__runtime-core.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__runtime-core/index.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/reactivity/package.json",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/reactivity.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@vue/reactivity/index.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__reactivity/package.json",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__reactivity.d.ts",
  "/node_modules/@vue/runtime-core/dist/node_modules/@types/vue__reactivity/index.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@vue/reactivity/package.json",
  "/node_modules/@vue/runtime-core/node_modules/@vue/reactivity.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@vue/reactivity/index.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__reactivity/package.json",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__reactivity.d.ts",
  "/node_modules/@vue/runtime-core/node_modules/@types/vue__reactivity/index.d.ts",
  "/node_modules/@vue/compiler-dom/dist/compiler-dom.d.ts.d.ts",
  "/node_modules/@vue/compiler-dom/dist/compiler-dom.d.ts/index.d.ts",
  "/node_modules/@vue/reactivity/dist/reactivity.d.ts.d.ts",
  "/node_modules/@vue/reactivity/dist/reactivity.d.ts/index.d.ts",
  "/node_modules/@vue/shared/dist/shared.d.ts.d.ts",
  "/node_modules/@vue/shared/dist/shared.d.ts/index.d.ts",
  "/node_modules/@vue/compiler-dom/dist/node_modules/@vue/compiler-core/package.json",
  "/node_modules/@vue/compiler-dom/dist/node_modules/@vue/compiler-core.d.ts",
  "/node_modules/@vue/compiler-dom/dist/node_modules/@vue/compiler-core/index.d.ts",
  "/node_modules/@vue/compiler-dom/dist/node_modules/@types/vue__compiler-core/package.json",
  "/node_modules/@vue/compiler-dom/dist/node_modules/@types/vue__compiler-core.d.ts",
  "/node_modules/@vue/compiler-dom/dist/node_modules/@types/vue__compiler-core/index.d.ts",
  "/node_modules/@vue/compiler-dom/node_modules/@vue/compiler-core/package.json",
  "/node_modules/@vue/compiler-dom/node_modules/@vue/compiler-core.d.ts",
  "/node_modules/@vue/compiler-dom/node_modules/@vue/compiler-core/index.d.ts",
  "/node_modules/@vue/compiler-dom/node_modules/@types/vue__compiler-core/package.json",
  "/node_modules/@vue/compiler-dom/node_modules/@types/vue__compiler-core.d.ts",
  "/node_modules/@vue/compiler-dom/node_modules/@types/vue__compiler-core/index.d.ts",
  "/node_modules/@vue/node_modules/@vue/compiler-core/package.json",
  "/node_modules/@vue/node_modules/@vue/compiler-core.d.ts",
  "/node_modules/@vue/node_modules/@vue/compiler-core/index.d.ts",
  "/node_modules/@vue/node_modules/@types/vue__compiler-core/package.json",
  "/node_modules/@vue/node_modules/@types/vue__compiler-core.d.ts",
  "/node_modules/@vue/node_modules/@types/vue__compiler-core/index.d.ts",
  "/node_modules/@vue/compiler-core.d.ts",
  "/node_modules/@vue/compiler-core/index.d.ts",
  "/node_modules/@types/vue__compiler-core/package.json",
  "/node_modules/@types/vue__compiler-core.d.ts",
  "/node_modules/@types/vue__compiler-core/index.d.ts",
  "/node_modules/@vue/reactivity/dist/node_modules/@vue/shared/package.json",
  "/node_modules/@vue/reactivity/dist/node_modules/@vue/shared.d.ts",
  "/node_modules/@vue/reactivity/dist/node_modules/@vue/shared/index.d.ts",
  "/node_modules/@vue/reactivity/dist/node_modules/@types/vue__shared/package.json",
  "/node_modules/@vue/reactivity/dist/node_modules/@types/vue__shared.d.ts",
  "/node_modules/@vue/reactivity/dist/node_modules/@types/vue__shared/index.d.ts",
  "/node_modules/@vue/reactivity/node_modules/@vue/shared/package.json",
  "/node_modules/@vue/reactivity/node_modules/@vue/shared.d.ts",
  "/node_modules/@vue/reactivity/node_modules/@vue/shared/index.d.ts",
  "/node_modules/@vue/reactivity/node_modules/@types/vue__shared/package.json",
  "/node_modules/@vue/reactivity/node_modules/@types/vue__shared.d.ts",
  "/node_modules/@vue/reactivity/node_modules/@types/vue__shared/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/compiler-core.d.ts.d.ts",
  "/node_modules/@vue/compiler-core/dist/compiler-core.d.ts/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@babel/types/package.json",
  "/node_modules/@vue/compiler-core/dist/node_modules/@babel/types.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@babel/types/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/babel__types/package.json",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/babel__types.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/babel__types/index.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@babel/types/package.json",
  "/node_modules/@vue/compiler-core/node_modules/@babel/types.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@babel/types/index.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@types/babel__types/package.json",
  "/node_modules/@vue/compiler-core/node_modules/@types/babel__types.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@types/babel__types/index.d.ts",
  "/node_modules/@vue/node_modules/@babel/types/package.json",
  "/node_modules/@vue/node_modules/@babel/types.d.ts",
  "/node_modules/@vue/node_modules/@babel/types/index.d.ts",
  "/node_modules/@vue/node_modules/@types/babel__types/package.json",
  "/node_modules/@vue/node_modules/@types/babel__types.d.ts",
  "/node_modules/@vue/node_modules/@types/babel__types/index.d.ts",
  "/node_modules/@babel/types.d.ts",
  "/node_modules/@babel/types/index.d.ts",
  "/node_modules/@types/babel__types/package.json",
  "/node_modules/@types/babel__types.d.ts",
  "/node_modules/@types/babel__types/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@vue/shared/package.json",
  "/node_modules/@vue/compiler-core/dist/node_modules/@vue/shared.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@vue/shared/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/vue__shared/package.json",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/vue__shared.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/vue__shared/index.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@vue/shared/package.json",
  "/node_modules/@vue/compiler-core/node_modules/@vue/shared.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@vue/shared/index.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@types/vue__shared/package.json",
  "/node_modules/@vue/compiler-core/node_modules/@types/vue__shared.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@types/vue__shared/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@babel/parser/package.json",
  "/node_modules/@vue/compiler-core/dist/node_modules/@babel/parser.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@babel/parser/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/babel__parser/package.json",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/babel__parser.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/babel__parser/index.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@babel/parser/package.json",
  "/node_modules/@vue/compiler-core/node_modules/@babel/parser.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@babel/parser/index.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@types/babel__parser/package.json",
  "/node_modules/@vue/compiler-core/node_modules/@types/babel__parser.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@types/babel__parser/index.d.ts",
  "/node_modules/@vue/node_modules/@babel/parser/package.json",
  "/node_modules/@vue/node_modules/@babel/parser.d.ts",
  "/node_modules/@vue/node_modules/@babel/parser/index.d.ts",
  "/node_modules/@vue/node_modules/@types/babel__parser/package.json",
  "/node_modules/@vue/node_modules/@types/babel__parser.d.ts",
  "/node_modules/@vue/node_modules/@types/babel__parser/index.d.ts",
  "/node_modules/@babel/parser.d.ts",
  "/node_modules/@babel/parser/index.d.ts",
  "/node_modules/@types/babel__parser.d.ts",
  "/node_modules/@types/babel__parser/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/source-map/package.json",
  "/node_modules/@vue/compiler-core/dist/node_modules/source-map.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/source-map/index.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/source-map/package.json",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/source-map.d.ts",
  "/node_modules/@vue/compiler-core/dist/node_modules/@types/source-map/index.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/source-map/package.json",
  "/node_modules/@vue/compiler-core/node_modules/source-map.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/source-map/index.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@types/source-map/package.json",
  "/node_modules/@vue/compiler-core/node_modules/@types/source-map.d.ts",
  "/node_modules/@vue/compiler-core/node_modules/@types/source-map/index.d.ts",
  "/node_modules/@vue/node_modules/source-map/package.json",
  "/node_modules/@vue/node_modules/source-map.d.ts",
  "/node_modules/@vue/node_modules/source-map/index.d.ts",
  "/node_modules/@vue/node_modules/@types/source-map/package.json",
  "/node_modules/@vue/node_modules/@types/source-map.d.ts",
  "/node_modules/@vue/node_modules/@types/source-map/index.d.ts",
  "/node_modules/source-map.d.ts",
  "/node_modules/source-map/index.d.ts",
  "/node_modules/@types/source-map.d.ts",
  "/node_modules/@types/source-map/index.d.ts"
];
